version: "3.7"
services:
  server-php:
    container_name: servidor_php
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ../:/www/html
    stdin_open: true
    links:
      - mariadb-server
    ports:
      - "8000:8000"

  mariadb-server:
    container_name: servidor_db
    image: mariadb
    ports:
      - "3307:3307"
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../.db_mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb-server:db
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb-server
      PMA_USER: root
      PMA_PASSWORD: root
    restart: unless-stopped