version: '3.8'

services:
  php:
    image: dariolopez05/symfony-app:latest
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html  # Cambiar a la ruta que quieres usar en el contenedor
    #volumes:
    #  - .:/var/www/html  # Montar el directorio de tu máquina local en /var/back del contenedor
    depends_on:
      database:
        condition: service_healthy
  
  nginx:
    image: dariolopez05/symfony-nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html  # Cambia a /var/back tambiénh
    depends_on:
      php:
        condition: service_started

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambié MYSQL_USER y MYSQL_PASSWORD a MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: Patinaje
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5  # Aumenté el número de reintentos para darle más margen al servicio de base de datos
      timeout: 10s

volumes:
  db_data:
