version: '3.8'

services:
  php:
    image: davidreinon/symfony-app:latest
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html  # Asegúrate de que se monte correctamente el directorio del proyecto
    entrypoint: ["sh", "-c", "composer install --no-interaction --prefer-dist && ./scripts/wait-for-it.sh database:3306 --timeout=60 -- docker-php-entrypoint php-fpm"]
    depends_on:
      database:
        condition: service_healthy
    environment:
      SYMFONY_ENV: prod
      DATABASE_URL: "mysql://root:root@database:3306/Patinaje"  # URL de la base de datos

  nginx:
    image: davidreinon/symfony-nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      php:
        condition: service_started

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambié MYSQL_USER y MYSQL_PASSWORD a MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: Patinaje
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5  # Aumenté el número de reintentos para darle más margen al servicio de base de datos
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8080:80"  # Puedes acceder a phpMyAdmin a través de http://<tu-ip>:8080
    environment:
      PMA_HOST: database  # Nombre del servicio de la base de datos
      PMA_USER: root      # Usuario de la base de datos
      PMA_PASSWORD: root  # Contraseña de la base de datos
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
