version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que el Dockerfile esté en la raíz del proyecto
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html  # Asegúrate de que se monte correctamente el directorio del proyecto
    entrypoint: ["./scripts/wait-for-it.sh", "database:3306", "--timeout=60", "--", "docker-php-entrypoint", "php-fpm"]
    depends_on:
      database:
        condition: service_healthy
    environment:
      SYMFONY_ENV: prod
      DATABASE_URL: "mysql://root:root@database:3306/Patinaje"  # URL de la base de datos

  nginx:
    image: davidreinon/symfony-nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      php:
        condition: service_started

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Patinaje
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5  # Aumenté el número de reintentos para darle más margen al servicio de base de datos
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"  # Acceso a phpMyAdmin en el puerto 8080
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
